### ISSUE TITLE
I am unable to login into my server

### ISSUE THREAD

**Issue by MechWarriorZero** [atomy/rustdroid#23]
I am unable to login into my server

**Comment by atomy** [comment]
Hi MechWarriorZero, is your server using web-rcon(+rcon.web 1) or source-rcon?
Usually there are issues with finding the right query-port for your server.

Try to find your server on the [battlemetrics.com](https://www.battlemetrics.com/) page, there the query port is being shown, for example: https://www.battlemetrics.com/servers/rust/26714562

![grafik](https://github.com/user-attachments/assets/561defb4-5527-4652-a40a-c427a5e1eea4)

**Comment by MechWarriorZero** [comment]
I enter the info correctly and I get an error

**Comment by atomy** [comment]
Do you happen to have special-characters in your password? I recall that being an issue when using web-rcon.

**Comment by MechWarriorZero** [comment]
nope, it wont let me enter the :

**Comment by MechWarriorZero** [comment]
never mind I able to login into my server

**Comment by atomy** [comment]
Nice!

May I ask what the issue was? What needs to be more clear on the server-add-Dialog?

**Comment by MechWarriorZero** [comment]
idk? no need to reply back, would like the banner to show my picture of my server

**Comment by atomy** [comment]
Yeah, I am working on this feature: https://github.com/atomy/rustdroid/issues/8

Glad to see it's working now.
